### ISSUE TITLE
`SimpleInterval` not defined when Cython is not compiled.

### ISSUE THREAD

**Issue by lukasz-migas** [mobiusklein/ms_deisotope#32]
Hi,

I noticed that when importing `from ms_deisotope.peak_dependency_network.intervals import SimpleInterval` when the Cython module was not built (therefore the `._c....` interface is not available, the `SimpleInterval` is not defined. 

This will lead to `ImportError` when importing e.g. `from ms_deisotope import deconvolute_peaks`.

I would be happy to make a PR to fix the issue.

**Comment by mobiusklein** [comment]
It was simple to fix and I had to put together a new release shortly in any case. It is now part of v0.0.54, published on PyPI.

I admit that I'd effectively ignored how the library behaves without the C extensions at this point since the automated release process generated pre-built wheels for most platforms now. Was this a scenario where the wheel wasn't available or was it a non-CPython runtime you were using?

**Comment by lukasz-migas** [comment]
Thanks for a swift action!

I usually don't use the pure Python code either but in this case the pre-built binaries were not available (Windows, python 3.11.9).
