### ISSUE TITLE
Creating a release of ms_deisotope

### ISSUE THREAD

**Issue by azzamallow** [mobiusklein/ms_deisotope#6]
Hello!

Just for some context, I have been working with @infusini to get ms_deisotope working for our project.

I have been working off master, though I noticed there have been commits going into master. This introduces a problem for me. I automatically checkout and build ms_deisotope, and without a release/tag there is a risk that I will be checking out new changes which may break how I use ms_deisotope.

Are you able to create a release and/or tag a version of ms_deisotope? This will allow me to checkout that version and know it is consistent, and gives me the flexibility to opt-in to new changes that you create.

Thanks for your time!

**Comment by mobiusklein** [comment]
I should be able to do that. I'll add a tag tomorrow morning. Is anything currently broken for you that I should fix before then?

I'm just finishing up a small patch to make tracking co-isolation possible and then I'll likely be leaving things alone for a bit. I also should learn to stop working off master now that I have people using the library.

I'll also be pinning the required `pyteomics` version because a 4.0 release is pending that will break everything.
